### ISSUE TITLE
Slack Integration 3: Add create and update endpoints

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#320]
# Feature
## Why is this feature being added?
Need a way to securely connect `PB` with `BE`.
Allow PB to manage the slack authentication with SlackAPI. 
Forward all events that need it to BE. 

## What should your feature do?
- [ ] Allow authenticated application to send `POST` and `GET` HTTP requests
- [ ] add `slack_user_create`  to `config/routes.rb`
- [ ] add `slack_user_update`  to `config/routes.rb`

**Comment by hpjaj** [comment]
Dependency: https://github.com/OperationCode/operationcode_backend/issues/318

**Comment by juliantrueflynn** [comment]
@wimo7083 just following up on this and figured I would put what I said in OC Slack chat in here if for whatever reason this task changes hands and for overall better logging.

This ticket contains out of date requirements. With PR #431 there's already `create` and `update` routes with controller actions setup. This means the only task left to do with is Apiary documentation. In order for me to do that the PR has to be merged.

Something important to note: `update` route finds the SlackUser to update from `id` passed through the route params ([see here](https://github.com/OperationCode/operationcode_backend/pull/431/files/9324031e42600a4a69d8635e7faf432756af4346#diff-a9e6fb83acebdef617eda4b74d40b1afR69)). How would Slack Bot know the SlackUser id?

Slack API does have an API response with `user.identity` that includes id. In the [Slack API documentation](https://api.slack.com/methods/users.identity) they made note of this:

> User IDs are not guaranteed to be globally unique across all Slack users. The combination of user ID and team ID, on the other hand, is guaranteed to be globally unique.

Since it's not unique as is, OC shouldn't rely on that for `update` route.

**Comment by wimo7083** [comment]
Closed due to changing of design.
