### ISSUE TITLE
Dashboard missing is_partner and rendering object values

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#330]
# Bug Report
## What is the current behavior?
In the admin dashboard one of the attributes for code_school is not appearing as an attribute along with not allowing this to be filterable.

In the admin dashboard some filters show object values. 

## What is the expected behavior?
`is_partner` should be in dashboard
object references should instead show values.

## What steps did you take to get this behavior?
Login to dashboard
1. see missing `is_partner` 
2. Try to dropdown `Locations` and `Taggings` and `Tag Taggins`

### Operating System
windows 10
### Browser
chrome
### Screenshots
![image](https://user-images.githubusercontent.com/10781353/39262854-e179fe78-487d-11e8-9a0b-981ea472a68b.png)

![image](https://user-images.githubusercontent.com/10781353/39262844-d80c88e2-487d-11e8-9c42-ccdc2cb28478.png)

**Comment by iorme1** [comment]
Hi, I'd like to work on this if it is still available. Thanks!

**Comment by hpjaj** [comment]
@iorme1 - it's yours!  Let me know if you have any questions.

**Comment by iorme1** [comment]
I have a few questions about this issue.  My first conclusion after looking at the codebase was that this bug is based on how ActiveAdmin was setup for this website.  After coming to that conclusion, I researched a bit on ActiveAdmin because I had never used it before.  It seems like "is_partner" was missing from the permit_params and in the 'index do end block' of app/admin/code_school.rb.  However, for the "Tag Taggings" "Taggings" and "Locations" attributes that show up as object memory locations instead of property values, I don't really know how those are being shown in the attribute filters in the first place.  I don't see them as attributes of the "code_school" model in the codebase, nor do I see those attributes in the permit_params of app/admin/code_school.rb.  So I guess I'm not understanding how these attributes are related to the code_school model or how they are even being shown at all on those attribute filters for code schools.  I'm assuming I need to have quite a bit of knowledge on ActiveAdmin to solve this issue that I may just not have.

**Comment by hpjaj** [comment]
@iorme1 - You would just need to add `is_partner` to the below file in the same way the other attributes are added there.  For example, `full_time`.

https://github.com/OperationCode/operationcode_backend/blob/master/app/admin/code_school.rb

If you want to learn more about ActiveAdmin, in general, Railscasts has an oldy but goody you can watch.

**Comment by hpjaj** [comment]
@iorme1 - As there has not been any response in PR, or any recent activity on this issue, we are assuming it has become abandoned.  We are marking it available for other members to contribute.

Here are [our contributing guidelines](https://github.com/OperationCode/operationcode/blob/master/CONTRIBUTING.md#guidelines-for-working-an-issue) which discuss the process and **timelines** for working an issue.  You are more than welcome to re-reserve the issue, if it remains marked as "Status: Available"!

**Comment by hpjaj** [comment]
Completed in https://github.com/OperationCode/operationcode_backend/pull/362
