### ISSUE TITLE
Sidekiq monitoring

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_backend#405]
# Add to dashboard sidekiq (job queue) monitoring
## Why is this feature being added?
Without getting into the technical details, setting up kubectl, there's not an easy way to monitor sidekiq jobs. 

Our recent job queue issue happened because we had a billion retries, and we had no idea that jobs were backing up. This would give a data point to the health of the queue. 

One solution: https://github.com/mperham/sidekiq/wiki/Monitoring

Would allow us to put our monitoring behind a dashboard like this: 
![image](https://user-images.githubusercontent.com/10781353/45705380-ab37f780-bb36-11e8-8ca9-8f422d6c727d.png)

## What should your feature do?

User friendly monitoring for sidekiq.

**Comment by robbkidd** [comment]
Related suggestion: migrate `ActiveJob` classes to be full-fledged `Sidekiq::Worker` classes to take full advantage of the Sidekiq Web dashboard. Otherwise details in the web UI about the current or past state of jobs is minimal. The necessary changes would not be too invasive and would result in more control over how jobs get queued, how many retries a job gets, and possibly clearer testing. For a clearer testing example, currently the test suite is queuing jobs from test runs into the same Redis database as the development environment, so if you have both running, your development Sidekiq job runner starts freaking out trying to run jobs for records that don't exist because the test deleted them.

**Comment by robbkidd** [comment]
The difference in the dashboard turns out to be small. Info for Sidekiq::Workers is less noisy because it doesn't talk about ActiveJob global IDs or ActiveJob::Deserialization errors wrapping the real error. 

### Sidekiq Web - Retries for `ActiveJob` jobs

![sidekiq with activejob](https://user-images.githubusercontent.com/517302/45849484-1ed93080-bd00-11e8-9ba0-f819aa45c4ce.png)

### Sidekiq Web - Retries for `Sidekiq::Worker` jobs
![sidekiq with sidekiq workers](https://user-images.githubusercontent.com/517302/45849494-21d42100-bd00-11e8-9b36-68b72bb810ee.png)

**Comment by wimo7083** [comment]
assigning to myself for @robbkidd
